### ISSUE TITLE
找不到withknowledge和withat

### ISSUE THREAD

**Issue by qiuyuebai123** [TsukamotoShuchi/ROCK#1]
你写的Judgement.py里需要从config里的yaml提取出withknowledge和withat参数吧，但是你给的yaml里没有这两个参数啊，咋整？？
![image](https://github.com/user-attachments/assets/9a1cc1cf-2eb8-4702-a8bb-66c10d6806cc)
![image](https://github.com/user-attachments/assets/cf02105d-1097-42e7-9509-a21cab1289ba)

**Comment by LixiaoTHU** [comment]
带有``part''字段的config才是rock模型，如configs/PartImageNet/PartImageNet_part_trades_awp_ema_8.yaml, 否则是不使用part的纯分类对照实验

**Comment by qiuyuebai123** [comment]
part loss=nan是怎么回事
![image](https://github.com/user-attachments/assets/a89b0ab3-ad0d-4cc3-adfc-a5c08b567b8c)

**Comment by qiuyuebai123** [comment]
为什么到后面pixel accuracy: 0.00、Current classification accuracy: 0.00、Current PGD classification accuracy: 0.00也不停下来
![image](https://github.com/user-attachments/assets/805ffab8-5382-4ac2-ad2b-e35f8eba62c7)
