### ISSUE TITLE
loss.py里没有FewFocalLoss、FewFocalLoss_v2函数啊

### ISSUE THREAD

**Issue by qiuyuebai123** [TsukamotoShuchi/ROCK#2]
![image](https://github.com/user-attachments/assets/b518d284-fc77-40d4-bb04-06f1e6019d8c)

![image](https://github.com/user-attachments/assets/923208fe-5409-44be-8d08-404c85b8904b)

**Comment by LixiaoTHU** [comment]
注释掉

**Comment by qiuyuebai123** [comment]
上一个问题怎么解决part loss=nan，Current pixel accuracy:0.00，Current classification accuracy: 0.00
